/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "COOK" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "ORDER" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "PIZZA" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "PIZZA_TYPE" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

/* Create Tables */

CREATE TABLE  "COOK"
(
	"ID" VARCHAR2(50) NOT NULL,
	"NAME" VARCHAR2(50) NULL,
	"COOK_STATUS" VARCHAR2(50) NULL
)
;

CREATE TABLE  "ORDER"
(
	"ID" VARCHAR2(50) NOT NULL,
	"ORDER_STATUS" VARCHAR2(50) NULL
)
;

CREATE TABLE  "PIZZA"
(
	"ID" VARCHAR2(50) NOT NULL,
	"SIZE" VARCHAR2(50) NULL,
	"PIZZA_TYPE_ID" VARCHAR2(50) NULL,
	"PIZZA_STATUS" VARCHAR2(50) NULL,
	"ORDER_ID" VARCHAR2(50) NULL,
	"COOK_ID" VARCHAR2(50) NULL
)
;

CREATE TABLE  "PIZZA_TYPE"
(
	"ID" VARCHAR2(50) NOT NULL,
	"NAME" VARCHAR2(30) NULL,
	"PRICE_S" NUMBER(8,2) NULL,
	"PRICE_M" NUMBER(8,2) NULL,
	"PRICE_L" NUMBER(8,2) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  "COOK"
 ADD CONSTRAINT "PK_COOK"
	PRIMARY KEY ("ID")
 USING INDEX;

ALTER TABLE  "ORDER"
 ADD CONSTRAINT "PK_ORDER"
	PRIMARY KEY ("ID")
 USING INDEX;

ALTER TABLE  "PIZZA"
 ADD CONSTRAINT "PK_PIZZA"
	PRIMARY KEY ("ID")
 USING INDEX;

ALTER TABLE  "PIZZA_TYPE"
 ADD CONSTRAINT "PK_MENU"
	PRIMARY KEY ("ID")
 USING INDEX;

/* Create Foreign Key Constraints */

ALTER TABLE  "PIZZA"
 ADD CONSTRAINT "FK_PIZZA_COOK"
	FOREIGN KEY ("COOK_ID") REFERENCES  "COOK" ("ID")
;

ALTER TABLE  "PIZZA"
 ADD CONSTRAINT "FK_PIZZA_ORDER"
	FOREIGN KEY ("ORDER_ID") REFERENCES  "ORDER" ("ID")
;

ALTER TABLE  "PIZZA"
 ADD CONSTRAINT "FK_PIZZA_TYPE"
	FOREIGN KEY ("PIZZA_TYPE_ID") REFERENCES  "PIZZA_TYPE" ("ID")
;