/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "COOK" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "ORDER" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "PIZZA" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "PIZZATYPE" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

/* Create Tables */

CREATE TABLE  "COOK"
(
	"ID" VARCHAR2(50) NOT NULL,
	"NAME" VARCHAR2(50) NULL,
	"COOKSTATUS" VARCHAR2(50) NULL
)
;

CREATE TABLE  "ORDER"
(
	"ID" VARCHAR2(50) NOT NULL,
	"ORDERSTATUS" VARCHAR2(50) NULL
)
;

CREATE TABLE  "PIZZA"
(
	"ID" VARCHAR2(50) NOT NULL,
	"PIZZASIZE" VARCHAR2(50) NULL,
	"PIZZATYPEID" VARCHAR2(50) NULL,
	"PIZZASTATUS" VARCHAR2(50) NULL,
	"ORDERID" VARCHAR2(50) NULL,
	"COOKID" VARCHAR2(50) NULL
)
;

CREATE TABLE  "PIZZATYPE"
(
	"ID" VARCHAR2(50) NOT NULL,
	"NAME" VARCHAR2(30) NULL,
	"PRICES" NUMBER(8,2) NULL,
	"PRICEM" NUMBER(8,2) NULL,
	"PRICEL" NUMBER(8,2) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  "COOK"
 ADD CONSTRAINT "PKCOOK"
	PRIMARY KEY ("ID");

ALTER TABLE  "ORDER"
 ADD CONSTRAINT "PKORDER"
	PRIMARY KEY ("ID");

ALTER TABLE  "PIZZA"
 ADD CONSTRAINT "PKPIZZA"
	PRIMARY KEY ("ID");

ALTER TABLE  "PIZZATYPE"
 ADD CONSTRAINT "PKMENU"
	PRIMARY KEY ("ID");

/* Create Foreign Key Constraints */

ALTER TABLE  "PIZZA"
 ADD CONSTRAINT "FKPIZZACOOK"
	FOREIGN KEY ("COOKID") REFERENCES  "COOK" ("ID")
;

ALTER TABLE  "PIZZA"
 ADD CONSTRAINT "FKPIZZAORDER"
	FOREIGN KEY ("ORDERID") REFERENCES  "ORDER" ("ID")
;

ALTER TABLE  "PIZZA"
 ADD CONSTRAINT "FKPIZZATYPE"
	FOREIGN KEY ("PIZZATYPEID") REFERENCES  "PIZZATYPE" ("ID")
;